### ISSUE TITLE
Misc Usability Features

### ISSUE THREAD

**Issue by wyhinton** [M-Adoo/rundo#2]
Hello,
Awesome library.
Just a few things I think would make the library more beginner friendly:

-  Having a link to the crates.io page would be useful!
- Example of implementing Rundo trait for a custom struct

**Comment by M-Adoo** [comment]
Thank you for your suggestion, but this library has not been iterated recently. Maybe I will continue to develop it in a few months

**Comment by wyhinton** [comment]
Sure
